### ISSUE TITLE
Code question - Credit_Risk_Model_and_Credit_Scorecard.ipynb

### ISSUE THREAD

**Issue by wahoo0001** [finlytics-hub/credit_risk_model#3]
Hi there.  Thank you for submitting this python code.  it is extremely helpful as I am trying to learn python after using sas for a number of years.

In the date columns section of your code I am getting a python error (see below).  I have worked on this more than a few days and I don't seem to be getting anywhere.  Any idea?  I am using the same lending club dataframe that you used.

Thank you!

date columns code

# convert date columns to datetime format and create a new column as a difference between today and the respective date
def date_columns(df, column):
    # store current month
    today_date = pd.to_datetime('2020-08-01')
    # convert to datetime format
    df[column] = pd.to_datetime(df[column], format = "%b-%y")
    # calculate the difference in months and add to a new column
    df['mths_since_' + column] = round(pd.to_numeric((today_date - df[column]) / np.timedelta64(1, 'M')))
    # make any resulting -ve values to be equal to the max date
    df['mths_since_' + column] = df['mths_since_' + column].apply(lambda x: df['mths_since_' + column].max() if x < 0 else x)
    # drop the original date column
    df.drop(columns = [column], inplace = True)
​
# apply to X_train
date_columns(X_train, 'earliest_cr_line')
date_columns(X_train, 'issue_d')
date_columns(X_train, 'last_pymnt_d')
date_columns(X_train, 'last_credit_pull_d')
​
# let's check these new columns
print(X_train['mths_since_earliest_cr_line'].describe())
print(X_train['mths_since_issue_d'].describe())
print(X_train['mths_since_last_pymnt_d'].describe())
print(X_train['mths_since_last_credit_pull_d'].describe())

Python output and error code

count    237437.000000
mean        319.338734
std          75.183712
min         236.000000
25%         262.000000
50%         298.000000
75%         357.000000
max         619.000000
Name: mths_since_earliest_cr_line, dtype: float64
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: mths_since_issue_d, dtype: float64
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: mths_since_last_pymnt_d, dtype: float64
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3079             try:
-> 3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'mths_since_last_credit_pull_d'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-23-5a0aa17f3aa3> in <module>
     25 print(X_train['mths_since_issue_d'].describe())
     26 print(X_train['mths_since_last_pymnt_d'].describe())
---> 27 print(X_train['mths_since_last_credit_pull_d'].describe())

~\anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3022             if self.columns.nlevels > 1:
   3023                 return self._getitem_multilevel(key)
-> 3024             indexer = self.columns.get_loc(key)
   3025             if is_integer(indexer):
   3026                 indexer = [indexer]

~\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:
-> 3082                 raise KeyError(key) from err
   3083 
   3084         if tolerance is not None:

KeyError: 'mths_since_last_credit_pull_d'

**Comment by finlytics-hub** [comment]
This error is most likely due to there being no column named `mths_since_last_credit_pull_d` in the `X_train` df after applying the `date_columns` function on `last_credit_pull_d`. Pls recheck if your `X_train` df has `last_credit_pull_d` column before applying the `date_columns` function and `mths_since_last_credit_pull_d` column after applying the same function.

**Comment by wahoo0001** [comment]
Thank you!
